name: Godot Export and Deploy to Web Branch

on: 
  push:
    branches:
      - main

jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Game

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Export game
      id: export
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true

    - name: Deploy to web branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b web
        git add -f build/
        git commit -m "Automated web export"
        git push -f origin web